#############################################################################
# Makefile for building: SnakeZzzz
# Generated by qmake (3.1) (Qt 5.9.4)
# Project:  SnakeZzzz.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile SnakeZzzz.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../SFML-2.4.2/include -I../SFML-2.4.2/lib -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake-qt5 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake-qt5 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SnakeZzzz1.0.0
DISTDIR = /home/zawartas/Pulpit/SnakeZzzz/.tmp/SnakeZzzz1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lsfml-audio -lsfml-graphics -lsfml-network -lsfml-window -lsfml-system 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		snake.cpp \
		gra.cpp \
		plansza.cpp \
		window.cpp \
		textnaekranie.cpp \
		object.cpp \
		inputtext.cpp 
OBJECTS       = main.o \
		snake.o \
		gra.o \
		plansza.o \
		window.o \
		textnaekranie.o \
		object.o \
		inputtext.o
DIST          = /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		SnakeZzzz.pro snake.h \
		gra.h \
		plansza.h \
		window.h \
		textnaekranie.h \
		object.h \
		inputtext.h main.cpp \
		snake.cpp \
		gra.cpp \
		plansza.cpp \
		window.cpp \
		textnaekranie.cpp \
		object.cpp \
		inputtext.cpp
QMAKE_TARGET  = SnakeZzzz
DESTDIR       = 
TARGET        = SnakeZzzz


first: all
	echo $(CXX) -v
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SnakeZzzz.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		SnakeZzzz.pro
	$(QMAKE) -o Makefile SnakeZzzz.pro -spec linux-g++
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/toolchain.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/qmake_use.prf:
/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
SnakeZzzz.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile SnakeZzzz.pro -spec linux-g++

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp window.h \
		../SFML-2.4.2/include/SFML/Graphics.hpp \
		../SFML-2.4.2/include/SFML/Window.hpp \
		../SFML-2.4.2/include/SFML/System.hpp \
		../SFML-2.4.2/include/SFML/Config.hpp \
		../SFML-2.4.2/include/SFML/System/Clock.hpp \
		../SFML-2.4.2/include/SFML/System/Export.hpp \
		../SFML-2.4.2/include/SFML/System/Time.hpp \
		../SFML-2.4.2/include/SFML/System/Err.hpp \
		../SFML-2.4.2/include/SFML/System/FileInputStream.hpp \
		../SFML-2.4.2/include/SFML/System/InputStream.hpp \
		../SFML-2.4.2/include/SFML/System/NonCopyable.hpp \
		../SFML-2.4.2/include/SFML/System/Lock.hpp \
		../SFML-2.4.2/include/SFML/System/MemoryInputStream.hpp \
		../SFML-2.4.2/include/SFML/System/Mutex.hpp \
		../SFML-2.4.2/include/SFML/System/Sleep.hpp \
		../SFML-2.4.2/include/SFML/System/String.hpp \
		../SFML-2.4.2/include/SFML/System/Utf.hpp \
		../SFML-2.4.2/include/SFML/System/Utf.inl \
		../SFML-2.4.2/include/SFML/System/String.inl \
		../SFML-2.4.2/include/SFML/System/Thread.hpp \
		../SFML-2.4.2/include/SFML/System/Thread.inl \
		../SFML-2.4.2/include/SFML/System/ThreadLocal.hpp \
		../SFML-2.4.2/include/SFML/System/ThreadLocalPtr.hpp \
		../SFML-2.4.2/include/SFML/System/ThreadLocalPtr.inl \
		../SFML-2.4.2/include/SFML/System/Vector2.hpp \
		../SFML-2.4.2/include/SFML/System/Vector2.inl \
		../SFML-2.4.2/include/SFML/System/Vector3.hpp \
		../SFML-2.4.2/include/SFML/System/Vector3.inl \
		../SFML-2.4.2/include/SFML/Window/Context.hpp \
		../SFML-2.4.2/include/SFML/Window/Export.hpp \
		../SFML-2.4.2/include/SFML/Window/GlResource.hpp \
		../SFML-2.4.2/include/SFML/Window/ContextSettings.hpp \
		../SFML-2.4.2/include/SFML/Window/Event.hpp \
		../SFML-2.4.2/include/SFML/Window/Joystick.hpp \
		../SFML-2.4.2/include/SFML/Window/Keyboard.hpp \
		../SFML-2.4.2/include/SFML/Window/Mouse.hpp \
		../SFML-2.4.2/include/SFML/Window/Sensor.hpp \
		../SFML-2.4.2/include/SFML/Window/Touch.hpp \
		../SFML-2.4.2/include/SFML/Window/VideoMode.hpp \
		../SFML-2.4.2/include/SFML/Window/Window.hpp \
		../SFML-2.4.2/include/SFML/Window/WindowHandle.hpp \
		../SFML-2.4.2/include/SFML/Window/WindowStyle.hpp \
		../SFML-2.4.2/include/SFML/Graphics/BlendMode.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Export.hpp \
		../SFML-2.4.2/include/SFML/Graphics/CircleShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Shape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Drawable.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderStates.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Transform.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Rect.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Rect.inl \
		../SFML-2.4.2/include/SFML/Graphics/Transformable.hpp \
		../SFML-2.4.2/include/SFML/Graphics/VertexArray.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Vertex.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Color.hpp \
		../SFML-2.4.2/include/SFML/Graphics/PrimitiveType.hpp \
		../SFML-2.4.2/include/SFML/Graphics/ConvexShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Font.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glyph.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Texture.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Image.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RectangleShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderTarget.hpp \
		../SFML-2.4.2/include/SFML/Graphics/View.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderTexture.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderWindow.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Shader.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glsl.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glsl.inl \
		../SFML-2.4.2/include/SFML/Graphics/Sprite.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Text.hpp \
		gra.h \
		plansza.h \
		snake.h \
		textnaekranie.h \
		object.h \
		../SFML-2.4.2/include/SFML/Audio.hpp \
		../SFML-2.4.2/include/SFML/Audio/InputSoundFile.hpp \
		../SFML-2.4.2/include/SFML/Audio/Export.hpp \
		../SFML-2.4.2/include/SFML/Audio/Listener.hpp \
		../SFML-2.4.2/include/SFML/Audio/Music.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundStream.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundSource.hpp \
		../SFML-2.4.2/include/SFML/Audio/AlResource.hpp \
		../SFML-2.4.2/include/SFML/Audio/OutputSoundFile.hpp \
		../SFML-2.4.2/include/SFML/Audio/Sound.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundBuffer.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundBufferRecorder.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundRecorder.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundFileFactory.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundFileFactory.inl \
		../SFML-2.4.2/include/SFML/Audio/SoundFileReader.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundFileWriter.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

snake.o: snake.cpp snake.h \
		../SFML-2.4.2/include/SFML/Graphics.hpp \
		../SFML-2.4.2/include/SFML/Window.hpp \
		../SFML-2.4.2/include/SFML/System.hpp \
		../SFML-2.4.2/include/SFML/Config.hpp \
		../SFML-2.4.2/include/SFML/System/Clock.hpp \
		../SFML-2.4.2/include/SFML/System/Export.hpp \
		../SFML-2.4.2/include/SFML/System/Time.hpp \
		../SFML-2.4.2/include/SFML/System/Err.hpp \
		../SFML-2.4.2/include/SFML/System/FileInputStream.hpp \
		../SFML-2.4.2/include/SFML/System/InputStream.hpp \
		../SFML-2.4.2/include/SFML/System/NonCopyable.hpp \
		../SFML-2.4.2/include/SFML/System/Lock.hpp \
		../SFML-2.4.2/include/SFML/System/MemoryInputStream.hpp \
		../SFML-2.4.2/include/SFML/System/Mutex.hpp \
		../SFML-2.4.2/include/SFML/System/Sleep.hpp \
		../SFML-2.4.2/include/SFML/System/String.hpp \
		../SFML-2.4.2/include/SFML/System/Utf.hpp \
		../SFML-2.4.2/include/SFML/System/Utf.inl \
		../SFML-2.4.2/include/SFML/System/String.inl \
		../SFML-2.4.2/include/SFML/System/Thread.hpp \
		../SFML-2.4.2/include/SFML/System/Thread.inl \
		../SFML-2.4.2/include/SFML/System/ThreadLocal.hpp \
		../SFML-2.4.2/include/SFML/System/ThreadLocalPtr.hpp \
		../SFML-2.4.2/include/SFML/System/ThreadLocalPtr.inl \
		../SFML-2.4.2/include/SFML/System/Vector2.hpp \
		../SFML-2.4.2/include/SFML/System/Vector2.inl \
		../SFML-2.4.2/include/SFML/System/Vector3.hpp \
		../SFML-2.4.2/include/SFML/System/Vector3.inl \
		../SFML-2.4.2/include/SFML/Window/Context.hpp \
		../SFML-2.4.2/include/SFML/Window/Export.hpp \
		../SFML-2.4.2/include/SFML/Window/GlResource.hpp \
		../SFML-2.4.2/include/SFML/Window/ContextSettings.hpp \
		../SFML-2.4.2/include/SFML/Window/Event.hpp \
		../SFML-2.4.2/include/SFML/Window/Joystick.hpp \
		../SFML-2.4.2/include/SFML/Window/Keyboard.hpp \
		../SFML-2.4.2/include/SFML/Window/Mouse.hpp \
		../SFML-2.4.2/include/SFML/Window/Sensor.hpp \
		../SFML-2.4.2/include/SFML/Window/Touch.hpp \
		../SFML-2.4.2/include/SFML/Window/VideoMode.hpp \
		../SFML-2.4.2/include/SFML/Window/Window.hpp \
		../SFML-2.4.2/include/SFML/Window/WindowHandle.hpp \
		../SFML-2.4.2/include/SFML/Window/WindowStyle.hpp \
		../SFML-2.4.2/include/SFML/Graphics/BlendMode.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Export.hpp \
		../SFML-2.4.2/include/SFML/Graphics/CircleShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Shape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Drawable.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderStates.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Transform.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Rect.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Rect.inl \
		../SFML-2.4.2/include/SFML/Graphics/Transformable.hpp \
		../SFML-2.4.2/include/SFML/Graphics/VertexArray.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Vertex.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Color.hpp \
		../SFML-2.4.2/include/SFML/Graphics/PrimitiveType.hpp \
		../SFML-2.4.2/include/SFML/Graphics/ConvexShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Font.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glyph.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Texture.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Image.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RectangleShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderTarget.hpp \
		../SFML-2.4.2/include/SFML/Graphics/View.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderTexture.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderWindow.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Shader.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glsl.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glsl.inl \
		../SFML-2.4.2/include/SFML/Graphics/Sprite.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Text.hpp \
		../SFML-2.4.2/include/SFML/Audio.hpp \
		../SFML-2.4.2/include/SFML/Audio/InputSoundFile.hpp \
		../SFML-2.4.2/include/SFML/Audio/Export.hpp \
		../SFML-2.4.2/include/SFML/Audio/Listener.hpp \
		../SFML-2.4.2/include/SFML/Audio/Music.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundStream.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundSource.hpp \
		../SFML-2.4.2/include/SFML/Audio/AlResource.hpp \
		../SFML-2.4.2/include/SFML/Audio/OutputSoundFile.hpp \
		../SFML-2.4.2/include/SFML/Audio/Sound.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundBuffer.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundBufferRecorder.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundRecorder.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundFileFactory.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundFileFactory.inl \
		../SFML-2.4.2/include/SFML/Audio/SoundFileReader.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundFileWriter.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o snake.o snake.cpp

gra.o: gra.cpp gra.h \
		plansza.h \
		../SFML-2.4.2/include/SFML/Graphics.hpp \
		../SFML-2.4.2/include/SFML/Window.hpp \
		../SFML-2.4.2/include/SFML/System.hpp \
		../SFML-2.4.2/include/SFML/Config.hpp \
		../SFML-2.4.2/include/SFML/System/Clock.hpp \
		../SFML-2.4.2/include/SFML/System/Export.hpp \
		../SFML-2.4.2/include/SFML/System/Time.hpp \
		../SFML-2.4.2/include/SFML/System/Err.hpp \
		../SFML-2.4.2/include/SFML/System/FileInputStream.hpp \
		../SFML-2.4.2/include/SFML/System/InputStream.hpp \
		../SFML-2.4.2/include/SFML/System/NonCopyable.hpp \
		../SFML-2.4.2/include/SFML/System/Lock.hpp \
		../SFML-2.4.2/include/SFML/System/MemoryInputStream.hpp \
		../SFML-2.4.2/include/SFML/System/Mutex.hpp \
		../SFML-2.4.2/include/SFML/System/Sleep.hpp \
		../SFML-2.4.2/include/SFML/System/String.hpp \
		../SFML-2.4.2/include/SFML/System/Utf.hpp \
		../SFML-2.4.2/include/SFML/System/Utf.inl \
		../SFML-2.4.2/include/SFML/System/String.inl \
		../SFML-2.4.2/include/SFML/System/Thread.hpp \
		../SFML-2.4.2/include/SFML/System/Thread.inl \
		../SFML-2.4.2/include/SFML/System/ThreadLocal.hpp \
		../SFML-2.4.2/include/SFML/System/ThreadLocalPtr.hpp \
		../SFML-2.4.2/include/SFML/System/ThreadLocalPtr.inl \
		../SFML-2.4.2/include/SFML/System/Vector2.hpp \
		../SFML-2.4.2/include/SFML/System/Vector2.inl \
		../SFML-2.4.2/include/SFML/System/Vector3.hpp \
		../SFML-2.4.2/include/SFML/System/Vector3.inl \
		../SFML-2.4.2/include/SFML/Window/Context.hpp \
		../SFML-2.4.2/include/SFML/Window/Export.hpp \
		../SFML-2.4.2/include/SFML/Window/GlResource.hpp \
		../SFML-2.4.2/include/SFML/Window/ContextSettings.hpp \
		../SFML-2.4.2/include/SFML/Window/Event.hpp \
		../SFML-2.4.2/include/SFML/Window/Joystick.hpp \
		../SFML-2.4.2/include/SFML/Window/Keyboard.hpp \
		../SFML-2.4.2/include/SFML/Window/Mouse.hpp \
		../SFML-2.4.2/include/SFML/Window/Sensor.hpp \
		../SFML-2.4.2/include/SFML/Window/Touch.hpp \
		../SFML-2.4.2/include/SFML/Window/VideoMode.hpp \
		../SFML-2.4.2/include/SFML/Window/Window.hpp \
		../SFML-2.4.2/include/SFML/Window/WindowHandle.hpp \
		../SFML-2.4.2/include/SFML/Window/WindowStyle.hpp \
		../SFML-2.4.2/include/SFML/Graphics/BlendMode.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Export.hpp \
		../SFML-2.4.2/include/SFML/Graphics/CircleShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Shape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Drawable.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderStates.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Transform.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Rect.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Rect.inl \
		../SFML-2.4.2/include/SFML/Graphics/Transformable.hpp \
		../SFML-2.4.2/include/SFML/Graphics/VertexArray.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Vertex.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Color.hpp \
		../SFML-2.4.2/include/SFML/Graphics/PrimitiveType.hpp \
		../SFML-2.4.2/include/SFML/Graphics/ConvexShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Font.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glyph.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Texture.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Image.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RectangleShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderTarget.hpp \
		../SFML-2.4.2/include/SFML/Graphics/View.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderTexture.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderWindow.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Shader.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glsl.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glsl.inl \
		../SFML-2.4.2/include/SFML/Graphics/Sprite.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Text.hpp \
		snake.h \
		window.h \
		textnaekranie.h \
		object.h \
		../SFML-2.4.2/include/SFML/Audio.hpp \
		../SFML-2.4.2/include/SFML/Audio/InputSoundFile.hpp \
		../SFML-2.4.2/include/SFML/Audio/Export.hpp \
		../SFML-2.4.2/include/SFML/Audio/Listener.hpp \
		../SFML-2.4.2/include/SFML/Audio/Music.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundStream.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundSource.hpp \
		../SFML-2.4.2/include/SFML/Audio/AlResource.hpp \
		../SFML-2.4.2/include/SFML/Audio/OutputSoundFile.hpp \
		../SFML-2.4.2/include/SFML/Audio/Sound.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundBuffer.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundBufferRecorder.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundRecorder.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundFileFactory.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundFileFactory.inl \
		../SFML-2.4.2/include/SFML/Audio/SoundFileReader.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundFileWriter.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gra.o gra.cpp

plansza.o: plansza.cpp plansza.h \
		../SFML-2.4.2/include/SFML/Graphics.hpp \
		../SFML-2.4.2/include/SFML/Window.hpp \
		../SFML-2.4.2/include/SFML/System.hpp \
		../SFML-2.4.2/include/SFML/Config.hpp \
		../SFML-2.4.2/include/SFML/System/Clock.hpp \
		../SFML-2.4.2/include/SFML/System/Export.hpp \
		../SFML-2.4.2/include/SFML/System/Time.hpp \
		../SFML-2.4.2/include/SFML/System/Err.hpp \
		../SFML-2.4.2/include/SFML/System/FileInputStream.hpp \
		../SFML-2.4.2/include/SFML/System/InputStream.hpp \
		../SFML-2.4.2/include/SFML/System/NonCopyable.hpp \
		../SFML-2.4.2/include/SFML/System/Lock.hpp \
		../SFML-2.4.2/include/SFML/System/MemoryInputStream.hpp \
		../SFML-2.4.2/include/SFML/System/Mutex.hpp \
		../SFML-2.4.2/include/SFML/System/Sleep.hpp \
		../SFML-2.4.2/include/SFML/System/String.hpp \
		../SFML-2.4.2/include/SFML/System/Utf.hpp \
		../SFML-2.4.2/include/SFML/System/Utf.inl \
		../SFML-2.4.2/include/SFML/System/String.inl \
		../SFML-2.4.2/include/SFML/System/Thread.hpp \
		../SFML-2.4.2/include/SFML/System/Thread.inl \
		../SFML-2.4.2/include/SFML/System/ThreadLocal.hpp \
		../SFML-2.4.2/include/SFML/System/ThreadLocalPtr.hpp \
		../SFML-2.4.2/include/SFML/System/ThreadLocalPtr.inl \
		../SFML-2.4.2/include/SFML/System/Vector2.hpp \
		../SFML-2.4.2/include/SFML/System/Vector2.inl \
		../SFML-2.4.2/include/SFML/System/Vector3.hpp \
		../SFML-2.4.2/include/SFML/System/Vector3.inl \
		../SFML-2.4.2/include/SFML/Window/Context.hpp \
		../SFML-2.4.2/include/SFML/Window/Export.hpp \
		../SFML-2.4.2/include/SFML/Window/GlResource.hpp \
		../SFML-2.4.2/include/SFML/Window/ContextSettings.hpp \
		../SFML-2.4.2/include/SFML/Window/Event.hpp \
		../SFML-2.4.2/include/SFML/Window/Joystick.hpp \
		../SFML-2.4.2/include/SFML/Window/Keyboard.hpp \
		../SFML-2.4.2/include/SFML/Window/Mouse.hpp \
		../SFML-2.4.2/include/SFML/Window/Sensor.hpp \
		../SFML-2.4.2/include/SFML/Window/Touch.hpp \
		../SFML-2.4.2/include/SFML/Window/VideoMode.hpp \
		../SFML-2.4.2/include/SFML/Window/Window.hpp \
		../SFML-2.4.2/include/SFML/Window/WindowHandle.hpp \
		../SFML-2.4.2/include/SFML/Window/WindowStyle.hpp \
		../SFML-2.4.2/include/SFML/Graphics/BlendMode.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Export.hpp \
		../SFML-2.4.2/include/SFML/Graphics/CircleShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Shape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Drawable.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderStates.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Transform.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Rect.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Rect.inl \
		../SFML-2.4.2/include/SFML/Graphics/Transformable.hpp \
		../SFML-2.4.2/include/SFML/Graphics/VertexArray.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Vertex.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Color.hpp \
		../SFML-2.4.2/include/SFML/Graphics/PrimitiveType.hpp \
		../SFML-2.4.2/include/SFML/Graphics/ConvexShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Font.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glyph.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Texture.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Image.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RectangleShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderTarget.hpp \
		../SFML-2.4.2/include/SFML/Graphics/View.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderTexture.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderWindow.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Shader.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glsl.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glsl.inl \
		../SFML-2.4.2/include/SFML/Graphics/Sprite.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Text.hpp \
		snake.h \
		../SFML-2.4.2/include/SFML/Audio.hpp \
		../SFML-2.4.2/include/SFML/Audio/InputSoundFile.hpp \
		../SFML-2.4.2/include/SFML/Audio/Export.hpp \
		../SFML-2.4.2/include/SFML/Audio/Listener.hpp \
		../SFML-2.4.2/include/SFML/Audio/Music.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundStream.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundSource.hpp \
		../SFML-2.4.2/include/SFML/Audio/AlResource.hpp \
		../SFML-2.4.2/include/SFML/Audio/OutputSoundFile.hpp \
		../SFML-2.4.2/include/SFML/Audio/Sound.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundBuffer.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundBufferRecorder.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundRecorder.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundFileFactory.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundFileFactory.inl \
		../SFML-2.4.2/include/SFML/Audio/SoundFileReader.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundFileWriter.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plansza.o plansza.cpp

window.o: window.cpp window.h \
		../SFML-2.4.2/include/SFML/Graphics.hpp \
		../SFML-2.4.2/include/SFML/Window.hpp \
		../SFML-2.4.2/include/SFML/System.hpp \
		../SFML-2.4.2/include/SFML/Config.hpp \
		../SFML-2.4.2/include/SFML/System/Clock.hpp \
		../SFML-2.4.2/include/SFML/System/Export.hpp \
		../SFML-2.4.2/include/SFML/System/Time.hpp \
		../SFML-2.4.2/include/SFML/System/Err.hpp \
		../SFML-2.4.2/include/SFML/System/FileInputStream.hpp \
		../SFML-2.4.2/include/SFML/System/InputStream.hpp \
		../SFML-2.4.2/include/SFML/System/NonCopyable.hpp \
		../SFML-2.4.2/include/SFML/System/Lock.hpp \
		../SFML-2.4.2/include/SFML/System/MemoryInputStream.hpp \
		../SFML-2.4.2/include/SFML/System/Mutex.hpp \
		../SFML-2.4.2/include/SFML/System/Sleep.hpp \
		../SFML-2.4.2/include/SFML/System/String.hpp \
		../SFML-2.4.2/include/SFML/System/Utf.hpp \
		../SFML-2.4.2/include/SFML/System/Utf.inl \
		../SFML-2.4.2/include/SFML/System/String.inl \
		../SFML-2.4.2/include/SFML/System/Thread.hpp \
		../SFML-2.4.2/include/SFML/System/Thread.inl \
		../SFML-2.4.2/include/SFML/System/ThreadLocal.hpp \
		../SFML-2.4.2/include/SFML/System/ThreadLocalPtr.hpp \
		../SFML-2.4.2/include/SFML/System/ThreadLocalPtr.inl \
		../SFML-2.4.2/include/SFML/System/Vector2.hpp \
		../SFML-2.4.2/include/SFML/System/Vector2.inl \
		../SFML-2.4.2/include/SFML/System/Vector3.hpp \
		../SFML-2.4.2/include/SFML/System/Vector3.inl \
		../SFML-2.4.2/include/SFML/Window/Context.hpp \
		../SFML-2.4.2/include/SFML/Window/Export.hpp \
		../SFML-2.4.2/include/SFML/Window/GlResource.hpp \
		../SFML-2.4.2/include/SFML/Window/ContextSettings.hpp \
		../SFML-2.4.2/include/SFML/Window/Event.hpp \
		../SFML-2.4.2/include/SFML/Window/Joystick.hpp \
		../SFML-2.4.2/include/SFML/Window/Keyboard.hpp \
		../SFML-2.4.2/include/SFML/Window/Mouse.hpp \
		../SFML-2.4.2/include/SFML/Window/Sensor.hpp \
		../SFML-2.4.2/include/SFML/Window/Touch.hpp \
		../SFML-2.4.2/include/SFML/Window/VideoMode.hpp \
		../SFML-2.4.2/include/SFML/Window/Window.hpp \
		../SFML-2.4.2/include/SFML/Window/WindowHandle.hpp \
		../SFML-2.4.2/include/SFML/Window/WindowStyle.hpp \
		../SFML-2.4.2/include/SFML/Graphics/BlendMode.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Export.hpp \
		../SFML-2.4.2/include/SFML/Graphics/CircleShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Shape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Drawable.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderStates.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Transform.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Rect.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Rect.inl \
		../SFML-2.4.2/include/SFML/Graphics/Transformable.hpp \
		../SFML-2.4.2/include/SFML/Graphics/VertexArray.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Vertex.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Color.hpp \
		../SFML-2.4.2/include/SFML/Graphics/PrimitiveType.hpp \
		../SFML-2.4.2/include/SFML/Graphics/ConvexShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Font.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glyph.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Texture.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Image.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RectangleShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderTarget.hpp \
		../SFML-2.4.2/include/SFML/Graphics/View.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderTexture.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderWindow.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Shader.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glsl.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glsl.inl \
		../SFML-2.4.2/include/SFML/Graphics/Sprite.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Text.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

textnaekranie.o: textnaekranie.cpp textnaekranie.h \
		../SFML-2.4.2/include/SFML/Graphics.hpp \
		../SFML-2.4.2/include/SFML/Window.hpp \
		../SFML-2.4.2/include/SFML/System.hpp \
		../SFML-2.4.2/include/SFML/Config.hpp \
		../SFML-2.4.2/include/SFML/System/Clock.hpp \
		../SFML-2.4.2/include/SFML/System/Export.hpp \
		../SFML-2.4.2/include/SFML/System/Time.hpp \
		../SFML-2.4.2/include/SFML/System/Err.hpp \
		../SFML-2.4.2/include/SFML/System/FileInputStream.hpp \
		../SFML-2.4.2/include/SFML/System/InputStream.hpp \
		../SFML-2.4.2/include/SFML/System/NonCopyable.hpp \
		../SFML-2.4.2/include/SFML/System/Lock.hpp \
		../SFML-2.4.2/include/SFML/System/MemoryInputStream.hpp \
		../SFML-2.4.2/include/SFML/System/Mutex.hpp \
		../SFML-2.4.2/include/SFML/System/Sleep.hpp \
		../SFML-2.4.2/include/SFML/System/String.hpp \
		../SFML-2.4.2/include/SFML/System/Utf.hpp \
		../SFML-2.4.2/include/SFML/System/Utf.inl \
		../SFML-2.4.2/include/SFML/System/String.inl \
		../SFML-2.4.2/include/SFML/System/Thread.hpp \
		../SFML-2.4.2/include/SFML/System/Thread.inl \
		../SFML-2.4.2/include/SFML/System/ThreadLocal.hpp \
		../SFML-2.4.2/include/SFML/System/ThreadLocalPtr.hpp \
		../SFML-2.4.2/include/SFML/System/ThreadLocalPtr.inl \
		../SFML-2.4.2/include/SFML/System/Vector2.hpp \
		../SFML-2.4.2/include/SFML/System/Vector2.inl \
		../SFML-2.4.2/include/SFML/System/Vector3.hpp \
		../SFML-2.4.2/include/SFML/System/Vector3.inl \
		../SFML-2.4.2/include/SFML/Window/Context.hpp \
		../SFML-2.4.2/include/SFML/Window/Export.hpp \
		../SFML-2.4.2/include/SFML/Window/GlResource.hpp \
		../SFML-2.4.2/include/SFML/Window/ContextSettings.hpp \
		../SFML-2.4.2/include/SFML/Window/Event.hpp \
		../SFML-2.4.2/include/SFML/Window/Joystick.hpp \
		../SFML-2.4.2/include/SFML/Window/Keyboard.hpp \
		../SFML-2.4.2/include/SFML/Window/Mouse.hpp \
		../SFML-2.4.2/include/SFML/Window/Sensor.hpp \
		../SFML-2.4.2/include/SFML/Window/Touch.hpp \
		../SFML-2.4.2/include/SFML/Window/VideoMode.hpp \
		../SFML-2.4.2/include/SFML/Window/Window.hpp \
		../SFML-2.4.2/include/SFML/Window/WindowHandle.hpp \
		../SFML-2.4.2/include/SFML/Window/WindowStyle.hpp \
		../SFML-2.4.2/include/SFML/Graphics/BlendMode.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Export.hpp \
		../SFML-2.4.2/include/SFML/Graphics/CircleShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Shape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Drawable.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderStates.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Transform.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Rect.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Rect.inl \
		../SFML-2.4.2/include/SFML/Graphics/Transformable.hpp \
		../SFML-2.4.2/include/SFML/Graphics/VertexArray.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Vertex.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Color.hpp \
		../SFML-2.4.2/include/SFML/Graphics/PrimitiveType.hpp \
		../SFML-2.4.2/include/SFML/Graphics/ConvexShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Font.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glyph.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Texture.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Image.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RectangleShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderTarget.hpp \
		../SFML-2.4.2/include/SFML/Graphics/View.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderTexture.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderWindow.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Shader.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glsl.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glsl.inl \
		../SFML-2.4.2/include/SFML/Graphics/Sprite.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Text.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textnaekranie.o textnaekranie.cpp

object.o: object.cpp object.h \
		../SFML-2.4.2/include/SFML/Graphics.hpp \
		../SFML-2.4.2/include/SFML/Window.hpp \
		../SFML-2.4.2/include/SFML/System.hpp \
		../SFML-2.4.2/include/SFML/Config.hpp \
		../SFML-2.4.2/include/SFML/System/Clock.hpp \
		../SFML-2.4.2/include/SFML/System/Export.hpp \
		../SFML-2.4.2/include/SFML/System/Time.hpp \
		../SFML-2.4.2/include/SFML/System/Err.hpp \
		../SFML-2.4.2/include/SFML/System/FileInputStream.hpp \
		../SFML-2.4.2/include/SFML/System/InputStream.hpp \
		../SFML-2.4.2/include/SFML/System/NonCopyable.hpp \
		../SFML-2.4.2/include/SFML/System/Lock.hpp \
		../SFML-2.4.2/include/SFML/System/MemoryInputStream.hpp \
		../SFML-2.4.2/include/SFML/System/Mutex.hpp \
		../SFML-2.4.2/include/SFML/System/Sleep.hpp \
		../SFML-2.4.2/include/SFML/System/String.hpp \
		../SFML-2.4.2/include/SFML/System/Utf.hpp \
		../SFML-2.4.2/include/SFML/System/Utf.inl \
		../SFML-2.4.2/include/SFML/System/String.inl \
		../SFML-2.4.2/include/SFML/System/Thread.hpp \
		../SFML-2.4.2/include/SFML/System/Thread.inl \
		../SFML-2.4.2/include/SFML/System/ThreadLocal.hpp \
		../SFML-2.4.2/include/SFML/System/ThreadLocalPtr.hpp \
		../SFML-2.4.2/include/SFML/System/ThreadLocalPtr.inl \
		../SFML-2.4.2/include/SFML/System/Vector2.hpp \
		../SFML-2.4.2/include/SFML/System/Vector2.inl \
		../SFML-2.4.2/include/SFML/System/Vector3.hpp \
		../SFML-2.4.2/include/SFML/System/Vector3.inl \
		../SFML-2.4.2/include/SFML/Window/Context.hpp \
		../SFML-2.4.2/include/SFML/Window/Export.hpp \
		../SFML-2.4.2/include/SFML/Window/GlResource.hpp \
		../SFML-2.4.2/include/SFML/Window/ContextSettings.hpp \
		../SFML-2.4.2/include/SFML/Window/Event.hpp \
		../SFML-2.4.2/include/SFML/Window/Joystick.hpp \
		../SFML-2.4.2/include/SFML/Window/Keyboard.hpp \
		../SFML-2.4.2/include/SFML/Window/Mouse.hpp \
		../SFML-2.4.2/include/SFML/Window/Sensor.hpp \
		../SFML-2.4.2/include/SFML/Window/Touch.hpp \
		../SFML-2.4.2/include/SFML/Window/VideoMode.hpp \
		../SFML-2.4.2/include/SFML/Window/Window.hpp \
		../SFML-2.4.2/include/SFML/Window/WindowHandle.hpp \
		../SFML-2.4.2/include/SFML/Window/WindowStyle.hpp \
		../SFML-2.4.2/include/SFML/Graphics/BlendMode.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Export.hpp \
		../SFML-2.4.2/include/SFML/Graphics/CircleShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Shape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Drawable.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderStates.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Transform.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Rect.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Rect.inl \
		../SFML-2.4.2/include/SFML/Graphics/Transformable.hpp \
		../SFML-2.4.2/include/SFML/Graphics/VertexArray.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Vertex.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Color.hpp \
		../SFML-2.4.2/include/SFML/Graphics/PrimitiveType.hpp \
		../SFML-2.4.2/include/SFML/Graphics/ConvexShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Font.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glyph.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Texture.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Image.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RectangleShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderTarget.hpp \
		../SFML-2.4.2/include/SFML/Graphics/View.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderTexture.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderWindow.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Shader.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glsl.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glsl.inl \
		../SFML-2.4.2/include/SFML/Graphics/Sprite.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Text.hpp \
		../SFML-2.4.2/include/SFML/Audio.hpp \
		../SFML-2.4.2/include/SFML/Audio/InputSoundFile.hpp \
		../SFML-2.4.2/include/SFML/Audio/Export.hpp \
		../SFML-2.4.2/include/SFML/Audio/Listener.hpp \
		../SFML-2.4.2/include/SFML/Audio/Music.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundStream.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundSource.hpp \
		../SFML-2.4.2/include/SFML/Audio/AlResource.hpp \
		../SFML-2.4.2/include/SFML/Audio/OutputSoundFile.hpp \
		../SFML-2.4.2/include/SFML/Audio/Sound.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundBuffer.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundBufferRecorder.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundRecorder.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundFileFactory.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundFileFactory.inl \
		../SFML-2.4.2/include/SFML/Audio/SoundFileReader.hpp \
		../SFML-2.4.2/include/SFML/Audio/SoundFileWriter.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object.o object.cpp

inputtext.o: inputtext.cpp inputtext.h \
		../SFML-2.4.2/include/SFML/Graphics.hpp \
		../SFML-2.4.2/include/SFML/Window.hpp \
		../SFML-2.4.2/include/SFML/System.hpp \
		../SFML-2.4.2/include/SFML/Config.hpp \
		../SFML-2.4.2/include/SFML/System/Clock.hpp \
		../SFML-2.4.2/include/SFML/System/Export.hpp \
		../SFML-2.4.2/include/SFML/System/Time.hpp \
		../SFML-2.4.2/include/SFML/System/Err.hpp \
		../SFML-2.4.2/include/SFML/System/FileInputStream.hpp \
		../SFML-2.4.2/include/SFML/System/InputStream.hpp \
		../SFML-2.4.2/include/SFML/System/NonCopyable.hpp \
		../SFML-2.4.2/include/SFML/System/Lock.hpp \
		../SFML-2.4.2/include/SFML/System/MemoryInputStream.hpp \
		../SFML-2.4.2/include/SFML/System/Mutex.hpp \
		../SFML-2.4.2/include/SFML/System/Sleep.hpp \
		../SFML-2.4.2/include/SFML/System/String.hpp \
		../SFML-2.4.2/include/SFML/System/Utf.hpp \
		../SFML-2.4.2/include/SFML/System/Utf.inl \
		../SFML-2.4.2/include/SFML/System/String.inl \
		../SFML-2.4.2/include/SFML/System/Thread.hpp \
		../SFML-2.4.2/include/SFML/System/Thread.inl \
		../SFML-2.4.2/include/SFML/System/ThreadLocal.hpp \
		../SFML-2.4.2/include/SFML/System/ThreadLocalPtr.hpp \
		../SFML-2.4.2/include/SFML/System/ThreadLocalPtr.inl \
		../SFML-2.4.2/include/SFML/System/Vector2.hpp \
		../SFML-2.4.2/include/SFML/System/Vector2.inl \
		../SFML-2.4.2/include/SFML/System/Vector3.hpp \
		../SFML-2.4.2/include/SFML/System/Vector3.inl \
		../SFML-2.4.2/include/SFML/Window/Context.hpp \
		../SFML-2.4.2/include/SFML/Window/Export.hpp \
		../SFML-2.4.2/include/SFML/Window/GlResource.hpp \
		../SFML-2.4.2/include/SFML/Window/ContextSettings.hpp \
		../SFML-2.4.2/include/SFML/Window/Event.hpp \
		../SFML-2.4.2/include/SFML/Window/Joystick.hpp \
		../SFML-2.4.2/include/SFML/Window/Keyboard.hpp \
		../SFML-2.4.2/include/SFML/Window/Mouse.hpp \
		../SFML-2.4.2/include/SFML/Window/Sensor.hpp \
		../SFML-2.4.2/include/SFML/Window/Touch.hpp \
		../SFML-2.4.2/include/SFML/Window/VideoMode.hpp \
		../SFML-2.4.2/include/SFML/Window/Window.hpp \
		../SFML-2.4.2/include/SFML/Window/WindowHandle.hpp \
		../SFML-2.4.2/include/SFML/Window/WindowStyle.hpp \
		../SFML-2.4.2/include/SFML/Graphics/BlendMode.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Export.hpp \
		../SFML-2.4.2/include/SFML/Graphics/CircleShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Shape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Drawable.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderStates.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Transform.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Rect.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Rect.inl \
		../SFML-2.4.2/include/SFML/Graphics/Transformable.hpp \
		../SFML-2.4.2/include/SFML/Graphics/VertexArray.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Vertex.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Color.hpp \
		../SFML-2.4.2/include/SFML/Graphics/PrimitiveType.hpp \
		../SFML-2.4.2/include/SFML/Graphics/ConvexShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Font.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glyph.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Texture.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Image.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RectangleShape.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderTarget.hpp \
		../SFML-2.4.2/include/SFML/Graphics/View.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderTexture.hpp \
		../SFML-2.4.2/include/SFML/Graphics/RenderWindow.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Shader.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glsl.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Glsl.inl \
		../SFML-2.4.2/include/SFML/Graphics/Sprite.hpp \
		../SFML-2.4.2/include/SFML/Graphics/Text.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inputtext.o inputtext.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

